### ISSUE TITLE
Error while running AssetIndexReader

### ISSUE THREAD

**Issue by BluSpring** [Razmoth/AssetIndexReader#4]
I extracted 31049740.blk, and ran AssetIndexReader on the resulting file (named `CAB-fd9412ebcd1f5b3ffcf31e6163a66032`) to create the .json file, but it just errors with this:
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'capacity')
   at System.Collections.Generic.Dictionary`2..ctor(Int32 capacity, IEqualityComparer`1 comparer)
   at AssetIndexReader.AssetIndex.ReadAssetTypeMap() in C:\Users\Razmoth\source\repos\AssetIndexReader\AssetIndexReader\AssetIndex.cs:line 41
   at AssetIndexReader.AssetIndex.Read() in C:\Users\Razmoth\source\repos\AssetIndexReader\AssetIndexReader\AssetIndex.cs:line 28
   at Program.<Main>$(String[] args) in C:\Users\Razmoth\source\repos\AssetIndexReader\AssetIndexReader\Program.cs:line 11
```

**Comment by Razmoth** [comment]
Greetings.

You'll need to extract the blk first, then open the CAB file again and extract the 0000006F.MiHoYoBinData inside of it [make sure that xor key is set to 0 in Export Options], use that as an input, should work fine
