### ISSUE TITLE
Can't extract assets_index.json from 0000006f.bin

### ISSUE THREAD

**Issue by 0eromacyS** [Razmoth/AssetIndexReader#6]
Greetings,

I extracted the the file `31049740.blk`
Load file `CAB-fd9412ebcd1f5b3ffcf31e6163a66032`
Set xor key to `0`
Export `0000006f.bin`

![image](https://user-images.githubusercontent.com/111354450/185016638-054fa68b-c76b-481d-8575-51f8af04afaf.png)

```
.\AssetIndexReader.exe .\0000006f.bin
```

return the following error:
```
Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at AssetIndexReader.AssetIndex.ReadAssetInfoMap() in C:\Users\Razmoth\source\repos\AssetIndexReader\AssetIndexReader\AssetIndex.cs:line 55
   at AssetIndexReader.AssetIndex.Read() in C:\Users\Razmoth\source\repos\AssetIndexReader\AssetIndexReader\AssetIndex.cs:line 29
   at Program.<Main>$(String[] args) in C:\Users\Razmoth\source\repos\AssetIndexReader\AssetIndexReader\Program.cs:line 11
```

**Comment by Razmoth** [comment]
Greetings,

In recent game versions the format has been changed, so it will no longer work with this tool.

**Comment by 0eromacyS** [comment]
> Greetings,
> 
> In recent game versions the format has been changed, so it will no longer work with this tool.

well,i see
thx
